title: "Alexander"
email: yweaner@hotmail.com
timezone: Asia/Shanghai
baseurl: "/"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: AlexanderChang
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: AlexanderChang
    display_name: AlexanderChang
    avatar: 'assets/images/sal.png'
    email: yweaner@hotmail.com
    web: https://www.sancuan.cn
    twitter: https://twitter.com/wowthemesnet
    description: "AlexanderChang 一个热爱家人、生活，一个热爱旅游、自然的Alexander！"

# Social
social:
  instagram: https://www.instagram.com/bootstrapstarter/
  facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives