# Menus (导航菜单配置)
menu:
    Home: / # 首页链接
    # Delete this row if you don't want categories in your header nav bar
    # 如果不想在导航栏显示分类，删除下面这行
    Categories: # 分类页面
    About: /about/index.html # 关于页面

# Customize (主题自定义配置)
customize:
    logo:
        width: 315 # logo宽度
        height: 90 # logo高度
        url: images/logo-header.png # logo图片路径
    theme_color: '#006bde' # 主题主色调
    highlight: androidstudio # 代码高亮主题
    sidebar: left # 侧边栏位置，可选：左侧(left)或右侧(right)
    thumbnail: true # 是否启用文章缩略图，可选：是(true)或否(false)
    favicon: css/images/font.png # 网站图标路径
    social_links: # 社交媒体链接，更多图标参见 http://fontawesome.io/icons/#brand
        # twitter: / # Twitter链接
        # facebook: / # Facebook链接
        # stack-overflow: / # Stack Overflow链接
        github: https://github.com/Yweaner # GitHub链接
        # weibo: / # 微博链接
        # rss: / # RSS订阅链接

# Widgets (侧边栏小工具)
widgets:
    - catalog # 目录
    - recent_posts # 最新文章
    - category # 分类
    - archive # 归档
    - tag # 标签
    - tagcloud # 标签云
    - links # 友情链接
    - google_adsense # 谷歌广告

# Search (搜索功能配置)
search:
    # insight: true # 使用Insight搜索，需要安装 hexo-generator-json-content 插件
    # swiftype: # Swiftype搜索服务密钥
    baidu: true # 百度搜索，启用时需要禁用其他搜索引擎

# Comment (评论系统配置)
comment:
    disqus: # Disqus评论系统的shortname
    duoshuo: # 多说评论系统ID
    youyan: # 友言评论系统ID
    facebook: # 是否启用Facebook评论
    isso: # Isso评论系统配置
        on: # 是否启用isso
        site: # isso服务器域名，如 comments.example.com
        lang: # 双字母语言代码，如 en
        reply-to-self: # 服务器垃圾评论防护设置
        require-author: # 服务器垃圾评论防护设置
        require-email: # 服务器垃圾评论防护设置
        max-comments-top: # 顶层评论显示数量，设置"inf"显示所有
        max-comments-nested: # 嵌套评论显示数量
        reveal-on-click: # 点击"隐藏"链接时显示的评论数
        avatar: # 是否启用头像生成
        avatar-bg: # 头像背景颜色，如"#f0f0f0"
        avatar-fg: # 头像前景色调色板(最多8个)，如"#9abf88 #5698c4 #e279a3 #9163b6"
        vote: # 是否启用投票功能
        vote-levels: # 自定义评论显示级别，如"[-5, 5, 15]"或"0,5,10"
    changyan: # 畅言评论系统
        appId: # 畅言应用ID
        appKey: # 畅言应用密钥
        on: # 是否启用
    valine: # Valine评论系统 https://github.com/xCss/Valine
        on: # 是否启用valine
        appId: # LeanCloud应用ID
        appKey: # LeanCloud应用密钥
        notify: # 是否启用邮件提醒
        verify: # 是否启用验证码
        placeholder: Just Do It # 评论框占位文本
        avatar: identicon # 头像配置选项
        avatar_cdn: https://gravatar.loli.net/avatar/ # 头像CDN地址
        pageSize: 10 # 每页评论数
        visitor: true # 是否启用阅读次数统计
        recordip: # 是否记录评论者IP
    gitalk: # Gitalk评论系统配置
        on: true # 是否启用gitalk
        owner: Yweaner # GitHub用户名
        repo: gitalk-comments # GitHub仓库名
        client_id: Ov23liNzml68fUUSkoxx # OAuth应用客户端ID
        client_secret: 3f112221ca27cc64a930b5c11234bcc1cfe640be # OAuth应用密钥
        admin: Yweaner # 可初始化评论的GitHub用户
        id: location.pathname # 页面唯一标识

# Share (分享功能配置)
share: default # 分享插件选择：jiathis, bdshare, addtoany, default

# Plugins (插件配置)
plugins:
    lightgallery: true # 图片画廊插件
    justifiedgallery: true # 图片排版插件
    google_analytics: # Google分析跟踪ID
    google_adsense: # Google广告
      publisher_id: # 发布商ID
      ad_slot: # 广告位ID
    baidu_analytics: # 百度统计哈希码
    bing_site_verification: # Bing站点验证码
    statcounter: # StatCounter统计配置
      sc_project: # StatCounter项目ID
      sc_invisible: # 设置1使统计器不可见
      sc_security: # 安全码
      public: # 设置true启用公开统计链接
      on: # 设置true启用StatCounter
    mathjax: false # 数学公式支持
    counter: false # 文章字数统计，需要安装hexo-wordcount插件
    cookie_consent: false # Cookie同意提示
    twitter_conversion_tracking: # Twitter转化跟踪
      enabled: false # 是否启用
      pixel_id: '' # 像素跟踪ID

# Miscellaneous (其他杂项配置)
miscellaneous:
    open_graph: # Open Graph协议配置
        fb_app_id: # Facebook应用ID
        fb_admins: # Facebook管理员ID
        twitter_id: # Twitter ID
    links: # 友情链接
        Hexo: http://hexo.io

poweredby: true # 是否显示Powered by信息